version: '2'
services:
    timerbe-app:
        image: timerbe
        external_links:
            - timerbe-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=timerbe
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    timerbe-mongodb:
        extends:
            file: mongodb.yml
            service: timerbe-mongodb
