version: '2'
services:
    timerbe-mongodb:
        container_name: timerbe-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/timerbe/mongodb/:/data/db/
